#:schema node_modules/wrangler/config-schema.json
name = "Kopral03"
main = "src/index.js"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "Kopral03", id = "1234" }
]
